In [3]:
import numpy as np
#陣列運算
oneArray = np.array([1,2,3,4,5])
oneArray*10/5

ModuleNotFoundError: No module named 'numpy'

In [3]:
twoArray = np.array([9,8,7,6,5])
oneArray+twoArray

array([10, 10, 10, 10, 10])

In [1]:
#統計
np.sum(oneArray), np.sum(twoArray)

NameError: name 'np' is not defined

In [6]:
#科學運算
np.log10(oneArray), np.log10(twoArray)

(array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ]),
 array([0.95424251, 0.90308999, 0.84509804, 0.77815125, 0.69897   ]))

In [2]:
np.zeros(10)
#快速建立二維資料
np.zeros((10,5))
#快速建立三維資料
np.zeros((10,5,3))


NameError: name 'np' is not defined

In [11]:
np.linspace(1,10,num=50).reshape(5,10)

array([[ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122],
       [ 2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592],
       [ 4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061],
       [ 6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531],
       [ 8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]])